- hosts: all 
  become: yes
  tasks: 
  - name: install apache2 on ubuntu 
    apt:
      name: apache2
      state: present
      update_cache: yes
    when:  ansible_os_family == "Debian"
  - name: install httpd on centos 
    yum: 
      name: httpd
      state: present 
    when: ansible_os_family == "RedHat"
