apiVersion: v1
kind: Pod
metadata: 
  name: appserver-pod   ## Pod Name
  labels: 
    appser: pod
spec: 
  containers: 
   - image: tomcat:8
     name: app-container  ## container name 
     ports: 
     - containerPort: 8080
       protocol: TCP 
       name: appport 
       
